apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Blueprints Workshop
  description: |
    A demonstration of some of the abilities of blueprints.
  author: XebiaLabs
  version: 1.0
  # TODO: Where is the binary to run this?
  instructions: Please read the generated file "xebialabs/USAGE.md" for further usage instructions.
spec:
  parameters:
  - name: AppName
    type: Input
    description: What name do you want to give the project?
    default: HelloWorld
  - name: ContainerPort
    type: Input
    description: At what port should the application be exposed in the container (1-65535)?
    default: 80
    pattern: "^()([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$"
  - name: HostPort
    type: Input
    description: At what port should the container port be mapped in the host?
    default: 8181
    pattern: "^()([1-9]|[1-5]?[0-9]{2,4}|6[1-4][0-9]{3}|65[1-4][0-9]{2}|655[1-2][0-9]|6553[1-5])$"
  - name: BackendDockerImage
    type: Select
    options:
    - xebialabsunsupported/rest-o-rant-api:v1
    - xebialabsunsupported/rest-o-rant-api:latest
    description: What is the Docker Image (repo and path) for the Backend service?
    default: "xebialabsunsupported/rest-o-rant-api:latest"
  - name: FrontendDockerImage
    type: Select
    options:
    - xebialabsunsupported/rest-o-rant-web:v1
    - xebialabsunsupported/rest-o-rant-web:latest
    description: What is the Docker Image (repo and path) for the Frontend service?
    default: "xebialabsunsupported/rest-o-rant-web:latest"
  - name: RunTestPhase
    type: Confirm
    description: Do you want to have a test phase?
  - name: TestPhaseColor
    type: Input
    description: What color would you like the test phase to be?
    default: "#FF0000"
    pattern: "^#([A-Fa-f0-9]{2}){2}[A-Fa-f0-9]{2}$"
    dependsOnTrue: RunTestPhase

